version: "3.8"

services:
  flask-mglobal-test-backend:
    container_name: "FlaskMGlobalTestBackend"
    build:
      context: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend/EmployeeData:/home/desarrollo/EmployeeData
    env_file:
      - envsThatShouldNotBeInRepo/dev_backend.env
    shm_size: "256mb" # Increase Shared Memory that is by default 64
    sysctls:
      - net.core.somaxconn=1024 # Increase the quantity og conections by default in 128
    command: /bin/sh -c "sleep 1000000; python app.py"